### ISSUE TITLE
Tracking camera

### ISSUE THREAD

**Issue by Zemanzo** [Zemanzo/web-marbles#32]
**Description**
A camera that automatically follows marbles to avoid the need to manually control the camera.

**Minimum Acceptance Criteria**
- [x] Used by default, for own marble.
- [x] Players can select marble that the camera should track by clicking the corresponding user in the list on the right.
- [x] Camera automatically tracks the selected marble.
- [x] Camera follows it whilst it rolls down the track.
- [x] When the selected player does not have a marble to track, it should move back to the default camera position (usually the start of a level).

**Related issues**
Switching cameras is described in #81
